name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: ECLint
      uses: snow-actions/eclint@v1.0.1
    - name: build and test
      run: mkdir build; cd build; cmake ..; make; ctest
    - name: build narucodec
      run: cd tools/naru_codec; mkdir build; cd build; cmake ..; make;
      
